package ibgo

import (
	"time"
)

// IbWrapper contain the funcs to handle the msg from TWS or Gateway
type IbWrapper interface {
	tickPrice(reqID int64, tickType int64, price float64, attrib TickAttrib)
	tickSize(reqID int64, tickType int64, size int64)
	orderStatus(orderID int64, status string, filled float64, remaining float64, avgFillPrice float64, permID int64, parentID int64, lastFillPrice float64, clientID int64, whyHeld string, mktCapPrice float64)
	error(reqID int64, errCode int64, errString string)
	openOrder(orderID int64, contract *Contract, order *Order, orderState *OrderState)
	updateAccountValue(tag string, val string, currency string, accName string)
	updatePortfolio(contract *Contract, position float64, marketPrice float64, marketValue float64, averageCost float64, unrealizedPNL float64, realizedPNL float64, accName string)
	updateAccountTime(accTime time.Time)
	nextValidID(reqID int64)
	contractDetails(reqID int64, conDetails *ContractDetails)
	execDetails(reqID int64, contract *Contract, execution *Execution)
	updateMktDepth(reqID int64, position int64, operation int64, side int64, price float64, size int64)
	updateMktDepthL2(reqID int64, position int64, marketMaker string, operation int64, side int64, price float64, size int64, isSmartDepth bool)
	updateNewsBulletin(msgID int64, msgType int64, newsMessage string, originExch string)
	managedAccounts(accountsList []string)
	receiveFA(faData int64, cxml string)
	historicalData(reqID int64, bar *BarData)
	historicalDataEnd(reqID int64, startDateStr string, endDateStr string)
	historicalDataUpdate(reqID int64, bar *BarData)
	bondContractDetails(reqID int64, conDetails *ContractDetails)
	scannerParameters(xml string)
	scannerData(reqID int64, rank int64, conDetails *ContractDetails, distance string, benchmark string, projection string, legs string)
	scannerDataEnd(reqID int64)
	tickOptionComputation(reqID int64, tickType int64, impliedVol float64, delta float64, optPrice float64, pvDiviedn float64, gamma float64, vega float64, theta float64, undPrice float64)
	tickGeneric(reqID int64, tickType int64, value float64)
	tickString(reqID int64, tickType int64, value string)
	tickEFP(reqID int64, tickType int64, basisPoints float64, formattedBasisPoints string, totalDividends float64, holdDays int64, futureLastTradeDate string, dividendImpact float64, dividendsToLastTradeDate float64)
	currentTime(t time.Time)
	realtimeBar(reqID int64, time int64, open float64, high float64, low float64, close float64, volume int64, wap float64, count int64)
	fundamentalData(reqID int64, data string)
	contractDetailsEnd(reqID int64)
	openOrderEnd()
	accountDownloadEnd(accName string)
	execDetailsEnd(reqID int64)
	deltaNeutralValidation(reqID int64, deltaNeutralContract DeltaNeutralContract)
	tickSnapshotEnd(reqID int64)
	marketDataType(reqID int64, marketDataType int64)
	position(account string, contract *Contract, position float64, avgCost float64)
	positionEnd()
	accountSummary(reqID int64, account string, tag string, value string, currency string)
	accountSummaryEnd(reqID int64)
	verifyMessageAPI(apiData string)
	verifyCompleted(isSuccessful bool, err string)
	displayGroupList(reqID int64, groups string)
	displayGroupUpdated(reqID int64, contractInfo string)
	verifyAndAuthMessageAPI(apiData string, xyzChallange string)
	verifyAndAuthCompleted(isSuccessful bool, err string)
	positionMulti(reqID int64, account string, modelCode string, contract *Contract, position float64, avgCost float64)
	positionMultiEnd(reqID int64)
	accountUpdateMulti(reqID int64, account string, modleCode string, tag string, value string, currency string)
	accountUpdateMultiEnd(reqID int64)
	securityDefinitionOptionParameter(reqID int64, exchange string, underlyingContractID int64, tradingClass string, multiplier string, expirations []string, strikes []float64)
	securityDefinitionOptionParameterEnd(reqID int64)
	softDollarTiers(reqID int64, tiers []SoftDollarTier)
	familyCodes(famCodes []FamilyCode)
	symbolSamples(reqID int64, contractDescriptions []ContractDescription)
	smartComponents(reqID int64, smartComps []SmartComponent)
	tickReqParams(tickerID int64, minTick float64, bboExchange string, snapshotPermissions int64)
	mktDepthExchanges(depthMktDataDescriptions []DepthMktDataDescription)
	headTimestamp(reqID int64, headTimestamp string)
	tickNews(tickerID int64, timeStamp int64, providerCode string, articleID string, headline string, extraData string)
	newsProviders(newsProviders []NewsProvider)
	newsArticle(reqID int64, articleType int64, articleText string)
	historicalNews(reqID int64, time string, providerCode string, articleID string, headline string)
	historicalNewsEnd(reqID int64, hasMore bool)
	histogramData(reqID int64, histogram []HistogramData)
	rerouteMktDataReq(reqID int64, contractID int64, exchange string)
	rerouteMktDepthReq(reqID int64, contractID int64, exchange string)
	marketRule(marketRuleID int64, priceIncrements []PriceIncrement)
	pnl(reqID int64, dailyPnL float64, unrealizedPnL float64, realizedPnL float64)
	pnlSingle(reqID int64, position int64, dailyPnL float64, unrealizedPnL float64, realizedPnL float64, value float64)
	historicalTicks(reqID int64, ticks []HistoricalTick, done bool)
	historicalTicksBidAsk(reqID int64, ticks []HistoricalTickBidAsk, done bool)
	historicalTicksLast(reqID int64, ticks []HistoricalTickLast, done bool)
	tickByTickAllLast(reqID int64, tickType int64, time int64, price float64, size int64, tickAttribLast TickAttribLast, exchange string, specialConditions string)
	tickByTickBidAsk(reqID int64, time int64, bidPrice float64, askPrice float64, bidSize int64, askSize int64, tickAttribBidAsk TickAttribBidAsk)
	tickByTickMidPoint(reqID int64, time int64, midPoint float64)
	orderBound(reqID int64, apiClientID int64, apiOrderID int64)

	commissionReport(commissionReport CommissionReport)
	connectAck()
}
